// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(WorkHubContext))]
    [Migration("20260821170953_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Application", b =>
                {
                    b.Property<string>("ApplicationId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("applicationId");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("appliedAt");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text")
                        .HasColumnName("coverLetter");

                    b.Property<string>("FinderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("finderId");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("jobId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("ApplicationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FinderId", "JobId" }, "finderId")
                        .IsUnique();

                    b.HasIndex(new[] { "JobId" }, "fk_application_job");

                    b.ToTable("application", (string)null);
                });

            modelBuilder.Entity("backend.Models.Employerprofile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("userId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("companyName");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("field");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("int")
                        .HasColumnName("foundedYear");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("logo");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("taxCode");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("website");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompanyName" }, "companyName")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("employerprofile", (string)null);
                });

            modelBuilder.Entity("backend.Models.Finderprofile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("userId");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar");

                    b.Property<string>("Cv")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CV");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("educationLevel");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Experience")
                        .HasColumnType("text")
                        .HasColumnName("experience");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Major")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Skill")
                        .HasColumnType("text")
                        .HasColumnName("skill");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasDatabaseName("email1");

                    b.ToTable("finderprofile", (string)null);
                });

            modelBuilder.Entity("backend.Models.Job", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("jobId");

                    b.Property<string>("ApplicantBenefit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("applicantBenefit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmployerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("employerId");

                    b.Property<ulong>("IsNegotiable")
                        .HasColumnType("bit(1)")
                        .HasColumnName("isNegotiable");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("jobTitle");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<int>("NumberOfPosition")
                        .HasColumnType("int")
                        .HasColumnName("numberOfPosition");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirement");

                    b.Property<int?>("Salary")
                        .HasColumnType("int")
                        .HasColumnName("salary");

                    b.Property<string>("SkillRequired")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("skillRequired");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("workType");

                    b.HasKey("JobId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmployerId" }, "fk_job_employer");

                    b.ToTable("job", (string)null);
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("userId");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("backend.Models.Application", b =>
                {
                    b.HasOne("backend.Models.Finderprofile", "Finder")
                        .WithMany("Applications")
                        .HasForeignKey("FinderId")
                        .IsRequired()
                        .HasConstraintName("fk_application_finder");

                    b.HasOne("backend.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("fk_application_job");

                    b.Navigation("Finder");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("backend.Models.Employerprofile", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithOne("Employerprofile")
                        .HasForeignKey("backend.Models.Employerprofile", "UserId")
                        .IsRequired()
                        .HasConstraintName("employerId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Finderprofile", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithOne("Finderprofile")
                        .HasForeignKey("backend.Models.Finderprofile", "UserId")
                        .IsRequired()
                        .HasConstraintName("finderId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Job", b =>
                {
                    b.HasOne("backend.Models.Employerprofile", "Employer")
                        .WithMany("Jobs")
                        .HasForeignKey("EmployerId")
                        .IsRequired()
                        .HasConstraintName("fk_job_employer");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("backend.Models.Employerprofile", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("backend.Models.Finderprofile", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("backend.Models.Job", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Employerprofile");

                    b.Navigation("Finderprofile");
                });
#pragma warning restore 612, 618
        }
    }
}
